include(FetchContent)

find_package(Git)
find_package(Threads REQUIRED)

FetchContent_Declare(libpng GIT_REPOSITORY https://github.com/pnggroup/libpng)
FetchContent_MakeAvailable(libpng)
if(NOT TARGET PNG::PNG)
	if(TARGET png_static)
        add_library(PNG ALIAS png_static)
		add_library(PNG::PNG ALIAS png_static)
	elseif(TARGET png)
        add_library(PNG ALIAS png)
		add_library(PNG::PNG ALIAS png)
	endif()
endif()

set(ZLIB_BUILD_SHARED OFF)
set(ZLIB_BUILD_STATIC ON)
FetchContent_Declare(zlib GIT_REPOSITORY https://github.com/madler/zlib GIT_TAG develop)
FetchContent_MakeAvailable(zlib)
if(NOT TARGET ZLIB::ZLIB)
	if(TARGET zlibstatic)
		add_library(ZLIB::ZLIB ALIAS zlibstatic)
	endif()
endif()

set(ZSTD_BUILD_SHARED OFF)
FetchContent_Declare(zstd GIT_REPOSITORY https://github.com/facebook/zstd GIT_TAG dev)
FetchContent_MakeAvailable(zstd)
if(NOT TARGET Zstd::Zstd)
	if(TARGET libzstd_static)
		add_library(Zstd::Zstd ALIAS libzstd_static)
	elseif(TARGET libzstd_shared)
		add_library(Zstd::Zstd ALIAS libzstd_shared)
	endif()
endif()

set(WEBP_LINK_STATIC ON)
set(WEBP_BUILD_CWEBP OFF)
set(WEBP_BUILD_DWEBP OFF)
set(WEBP_BUILD_GIF2WEBP OFF)
set(WEBP_BUILD_IMG2WEBP OFF)
set(WEBP_BUILD_VWEBP OFF)
set(WEBP_BUILD_WEBPINFO OFF)
set(WEBP_BUILD_WEBPMUX OFF)
set(WEBP_BUILD_EXTRAS OFF)
set(WEBP_BUILD_ANIM_UTILS OFF)
FetchContent_Declare(libwebp GIT_REPOSITORY https://github.com/webmproject/libwebp GIT_TAG main)
FetchContent_MakeAvailable(libwebp)
if(NOT TARGET WebP::libwebp)
	if(TARGET webp)
		add_library(WebP::libwebp ALIAS webp)
	endif()
endif()

set(BUILD_SHARED_LIBS OFF)
FetchContent_Declare(freetype GIT_REPOSITORY https://github.com/freetype/freetype)
FetchContent_MakeAvailable(freetype)
if(NOT TARGET Freetype::Freetype)
	if(TARGET freetype)
		add_library(Freetype::Freetype ALIAS freetype)
	endif()
endif()

set(BUILD_SHARED_LIBS OFF)
FetchContent_Declare(plutosvg GIT_REPOSITORY https://github.com/sammycage/plutosvg)
FetchContent_MakeAvailable(plutosvg)
if(NOT TARGET plutosvg::plutosvg)
	if(TARGET plutosvg)
		add_library(plutosvg::plutosvg ALIAS plutosvg)
	endif()
endif()

# set(BUILD_SHARED_LIBS OFF)
FetchContent_Declare(rapidyaml GIT_REPOSITORY https://github.com/biojppm/rapidyaml)
FetchContent_MakeAvailable(rapidyaml)
if(NOT TARGET ryml::ryml)
	if(TARGET ryml)
		add_library(ryml::ryml ALIAS ryml)
	endif()
endif()

set(SDL_STATIC ON)
FetchContent_Declare(sdl GIT_REPOSITORY https://github.com/libsdl-org/sdl GIT_TAG main)
FetchContent_MakeAvailable(sdl)


add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/ccc" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/cpuinfo" EXCLUDE_FROM_ALL)
set(USE_AUDIOUNIT OFF)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/cubeb" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/demangler" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/fast_float" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/fmt" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/freesurround" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/imgui" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/libchdr" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/libzip" EXCLUDE_FROM_ALL)
set(BUILD_STATIC_LIBS ON)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/lz4/build/cmake" EXCLUDE_FROM_ALL)
if(NOT TARGET LZ4::LZ4)
	if(TARGET lz4_static)
		add_library(LZ4::LZ4 ALIAS lz4_static)
	endif()
endif()
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/lzma" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/rcheevos" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/simpleini" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/soundtouch" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/vixl" EXCLUDE_FROM_ALL)
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/vulkan" EXCLUDE_FROM_ALL)


#[[
add_subdirectory("${CMAKE_SOURCE_DIR}/3rdparty/glslang" EXCLUDE_FROM_ALL)
]]